name: Master branch tagging
on:
 push:
  branches:
   - master

jobs:
 Tag:
  name: Create tag
  runs-on: ubuntu-latest
  outputs:
   tag: ${{ steps.version.outputs.current-version }}
   tag_created: ${{ steps.create-push-tag.outcome }}
  steps:
   - name: Check out repo
     uses: actions/checkout@v4
     with:
      ref: master
      fetch-depth: 0 # Necessario per avere la storia completa
   - name: Get version
     id: version
     uses: martinbeentjes/npm-get-version-action@main
   - name: Create and push tag
     id: create-push-tag
     continue-on-error: true
     run: |
      git config user.name "GitHub Actions"
      git config user.email "actions@github.com"
      TAG="v${{ steps.version.outputs.current-version }}"
      if git rev-parse "$TAG" >/dev/null 2>&1; then
        echo "Tag $TAG already exists"
        exit 1
      fi
      git tag "$TAG"
      git push origin "$TAG"

 Release:
  name: Create release
  runs-on: ubuntu-latest
  needs: Tag
  if: needs.Tag.outputs.tag_created == 'success'
  steps:
   - name: Check out repo
     uses: actions/checkout@v4
     with:
      ref: master
      fetch-depth: 0
   - name: Create and push release
     uses: fregante/release-with-changelog@v3
     with:
      token: ${{ secrets.GT }}
      exclude: "^Merge"
      commit-template: "- {date} | {title} ← {hash}"
      template: |
       ### Changelog
       {range}
       {commits}
